keycloak:
  enabled: true
  keycloak:
    resources:
      limits:
        cpu: 1
        memory: "2048Mi"
      requests:
        cpu: "300m"
        memory: "512Mi"
    username: admin
    password: admin
    persistence:
      deployPostgres: false
      dbVendor: H2
    livenessProbe:
      initialDelaySeconds: 100
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    extraVolumes: |
      - name: realm-secret
        secret:
          secretName: {{ .Release.Name }}-realm-secret
    extraVolumeMounts: |
      - name: realm-secret
        mountPath: "/realm/"
        readOnly: true
    extraArgs: -Dkeycloak.import=activiti-realm.json
    preStartScript: |
      /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
      /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
      cp /realm/activiti-realm.json .

## Define custom ingress resource for Keycloak to run on the gateway host domain
ingress:
  enabled: true
  path: "{{ include \"common.keycloak-path\" $ }}" # Uses global.keycloak.path template
  proxyBufferSize: "16k"
  hostName: # overrides global.gateway.host value
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'Access-Control-Allow-Methods: "POST, GET, OPTIONS, PUT, PATCH, DELETE"';
      more_set_headers 'Access-Control-Allow-Credentials: true';
      more_set_headers 'Access-Control-Allow-Headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,authorization"';
      more_set_headers 'Access-Control-Allow-Origin: $http_origin';
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

#extensions to the activiti base realm
realm:
#  extraRealmRoles:
#    - name: "ACTIVITI_TEST"
#    - name: "ACTIVITI_SUPER"
#  extraGroups:
#    - name: "ACTIVITI_GROUP"
#  extraUsers:
#    - username: superadminuser
#      enabled: true
#      firstName: "Super Admin"
#      lastName: User
#      email: "superadminuser@test.com"
#      credentials:
#      - type: password
#        value: password
#      realmRoles:
#        - "offline_access"
#        - "uma_authorization"
#        - "ACTIVITI_USER"
#      clientRoles:
#        account:
#          - "manage-account"
#          - "view-profile"
#      groups:
#        - "hr"
  activiti:
    webOrigins:
      - "*"
    redirectUris:
      - "*"
